#server:
#  port: 8082
  # ?? ??
#  port: 0
#spring:
#  application:
#    name: escape-server

#eureka:
##  instance:
#  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: oauth2
  security:
    user:
      name: ssafy
      password: ssafy
  datasource:
    url: jdbc:mysql://localhost:3306/eroom?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include:
      - oauth
#      - aws
#      - credentials
  jackson:
    property-naming-strategy: SNAKE_CASE


#logging:
#  level.org.springframework: debug
#  level.org.springframework.web: debug

# cors ??
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

# jwt secret key ??
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  secret: ENC(jGKmciAnyrtj+Ht6hzsC7fHv9R67FxH38qJdsn+km/fYNaz/xxzfpB90la/9tlAXubj7mKZvbqmaC98Th/3xeA4SWIYTo++VzTnqZxOZbrwOCf3m2qn5YXo6EbgFH02G)

# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ssafy
#    password : ENC(QxiQKa7GkBsypVEVvAqpVQ==)

# ?? ?? secret Key ? RedirectUri ??
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect