#server:
#  port: 8082
##  port: 0
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:flushed:{spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://j6c203.p.ssafy.io:8761/eureka

spring:
  application:
    name: escape-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://j6c203.p.ssafy.io:3306/escape?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: escape
    password: escape
#  datasource:
#    url: jdbc:mysql://localhost:3306/escape?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: ssafy
#    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include:
      - oauth
#      - aws
#      - credentials
  jackson:
    property-naming-strategy: SNAKE_CASE

#logging:
#  level.org.springframework: debug
#  level.org.springframework.web: debug